// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ManCmd_.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MANCMD__H_
#define _MANCMD__H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ManCmd__SOURCE)
#define ManCmd__DllAPI __declspec( dllexport )
#else
#define ManCmd__DllAPI __declspec( dllimport )
#endif // ManCmd__SOURCE
#else
#define ManCmd__DllAPI
#endif
#else
#define ManCmd__DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure ManCmd_ defined by the user in the IDL file.
 * @ingroup MANCMD_
 */
class ManCmd_
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ManCmd_();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ManCmd_();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ManCmd_ that will be copied.
     */
    eProsima_user_DllExport ManCmd_(const ManCmd_ &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ManCmd_ that will be copied.
     */
    eProsima_user_DllExport ManCmd_(ManCmd_ &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ManCmd_ that will be copied.
     */
    eProsima_user_DllExport ManCmd_& operator=(const ManCmd_ &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ManCmd_ that will be copied.
     */
    eProsima_user_DllExport ManCmd_& operator=(ManCmd_ &&x);

    /*!
     * @brief This function sets a value in member steer
     * @param _steer New value for member steer
     */
    eProsima_user_DllExport void steer(float _steer);

    /*!
     * @brief This function returns the value of member steer
     * @return Value of member steer
     */
    eProsima_user_DllExport float steer() const;

    /*!
     * @brief This function returns a reference to member steer
     * @return Reference to member steer
     */
    eProsima_user_DllExport float& steer();

    /*!
     * @brief This function sets a value in member throttle
     * @param _throttle New value for member throttle
     */
    eProsima_user_DllExport void throttle(float _throttle);

    /*!
     * @brief This function returns the value of member throttle
     * @return Value of member throttle
     */
    eProsima_user_DllExport float throttle() const;

    /*!
     * @brief This function returns a reference to member throttle
     * @return Reference to member throttle
     */
    eProsima_user_DllExport float& throttle();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const ManCmd_& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    float m_steer;
    float m_throttle;
};

#endif // _MANCMD__H_