// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file NavPose2d_.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "NavPose2d_.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

NavPose2d_::NavPose2d_()
{
    // m_x com.eprosima.idl.parser.typecode.PrimitiveTypeCode@13c27452
    m_x = 0.0;
    // m_y com.eprosima.idl.parser.typecode.PrimitiveTypeCode@262b2c86
    m_y = 0.0;
    // m_yaw com.eprosima.idl.parser.typecode.PrimitiveTypeCode@371a67ec
    m_yaw = 0.0;

}

NavPose2d_::~NavPose2d_()
{



}

NavPose2d_::NavPose2d_(const NavPose2d_ &x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_yaw = x.m_yaw;
}

NavPose2d_::NavPose2d_(NavPose2d_ &&x)
{
    m_x = x.m_x;
    m_y = x.m_y;
    m_yaw = x.m_yaw;
}

NavPose2d_& NavPose2d_::operator=(const NavPose2d_ &x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_yaw = x.m_yaw;

    return *this;
}

NavPose2d_& NavPose2d_::operator=(NavPose2d_ &&x)
{

    m_x = x.m_x;
    m_y = x.m_y;
    m_yaw = x.m_yaw;

    return *this;
}

size_t NavPose2d_::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t NavPose2d_::getCdrSerializedSize(const NavPose2d_& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void NavPose2d_::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_x;
    scdr << m_y;
    scdr << m_yaw;
}

void NavPose2d_::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_x;
    dcdr >> m_y;
    dcdr >> m_yaw;
}

/*!
 * @brief This function sets a value in member x
 * @param _x New value for member x
 */
void NavPose2d_::x(float _x)
{
m_x = _x;
}

/*!
 * @brief This function returns the value of member x
 * @return Value of member x
 */
float NavPose2d_::x() const
{
    return m_x;
}

/*!
 * @brief This function returns a reference to member x
 * @return Reference to member x
 */
float& NavPose2d_::x()
{
    return m_x;
}

/*!
 * @brief This function sets a value in member y
 * @param _y New value for member y
 */
void NavPose2d_::y(float _y)
{
m_y = _y;
}

/*!
 * @brief This function returns the value of member y
 * @return Value of member y
 */
float NavPose2d_::y() const
{
    return m_y;
}

/*!
 * @brief This function returns a reference to member y
 * @return Reference to member y
 */
float& NavPose2d_::y()
{
    return m_y;
}

/*!
 * @brief This function sets a value in member yaw
 * @param _yaw New value for member yaw
 */
void NavPose2d_::yaw(float _yaw)
{
m_yaw = _yaw;
}

/*!
 * @brief This function returns the value of member yaw
 * @return Value of member yaw
 */
float NavPose2d_::yaw() const
{
    return m_yaw;
}

/*!
 * @brief This function returns a reference to member yaw
 * @return Reference to member yaw
 */
float& NavPose2d_::yaw()
{
    return m_yaw;
}


size_t NavPose2d_::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool NavPose2d_::isKeyDefined()
{
   return false;
}

void NavPose2d_::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
     
     
}
